version: "3"
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reference_data
    ports:
      - "5432:5432"
