application:
  api-key: ${API_KEY:tst}
  catalog-admin-uri: ${CATALOG_ADMIN_SERVICE_URI:https://catalog-admin-service.staging.fellesdatakatalog.digdir.no}
  cors.originPatterns: ${CORS_ORIGIN_PATTERNS:*}

spring:
  http.codecs.max-in-memory-size: 2MB
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/${POSTGRESQL_DB:reference_data}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /reference-data
  compression:
    enabled: true
    mime-types: application/json
    tomcat:
      compression: on

management:
  endpoints:
    web:
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: reference-data
springdoc.api-docs.version: openapi_3_0
graphiql:
  cdn:
    enabled: true

logging:
  level:
    root: WARN
    no.*: ${LOG_LEVEL:INFO}
    org.springframework.*: WARN
    org.apache.jena.*: ERROR

---

spring:
  config.activate.on-profile: develop,unit-integration
  datasource:
    url: jdbc:postgresql://localhost:5432/reference_data
    username: root
    password: password
server:
  port: 8113
  servlet:
    context-path: /

management:
  statsd:
    metrics:
      export:
        enabled: false
---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/reference_data
    username: root
    password: password
server:
  servlet:
    context-path: /

management:
  statsd:
    metrics:
      export:
        enabled: false
