---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - reference-data-deployment.yaml
  - reference-data-service.yaml
images:
  - name: reference-data
    newName: ghcr.io/informasjonsforvaltning/fdk-reference-data
    newTag: $(GIT_COMMIT_SHA)
