---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: reference-data
  name: reference-data
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: reference-data
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: reference-data
    spec:
      containers:
        - name: reference-data
          image: reference-data
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "25m"
            limits:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /reference-data/actuator/ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /reference-data/actuator/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
