spring:
logging:
  level.root: ERROR
  level.o.a: ERROR
  level.o.apache: ERROR
  level.no.brreg: ERROR
  level.no.difi: ERROR
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/ld+json
    tomcat:
        compression: on
application:
  httpUsername: ${themesHttpUsername:user}
  httpPassword: ${themesHttpPassword:password}

management:
  endpoints.web.exposure.include: health, readiness

---

spring:
  profiles: develop,unit-integration
server:
  port: 8113


