package no.fdk.referencedata.settings;

public enum Settings {
    ACCESS_RIGHT,
    ADMINISTRATIVE_ENHETER,
    AUDIENCE_TYPE,
    RELATIONSHIP_WITH_SOURCE_TYPE,
    CONCEPT_STATUS,
    DATA_THEME,
    DATASET_TYPE,
    DISTRIBUTION_STATUS,
    DISTRIBUTION_TYPE,
    EVIDENCE_TYPE,
    FILE_TYPE,
    FREQUENCY,
    EURO_VOC,
    MEDIA_TYPE,
    GEONORGE_KOMMUNE,
    GEONORGE_FYLKE,
    MAIN_ACTIVITY,
    ROLE_TYPE,
    SERVICE_CHANNEL_TYPE
}
