name: Build, test and deploy to production on merge to master branch

on:
  push:
    branches:
      - master

jobs:
  build-test-and-deploy-production:
    name: Build, test, publish and deploy to production environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_FDK_JENKINS_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_FDK_JENKINS_GCR }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Package with maven
        run: mvn clean package --no-transfer-progress

      - name: Build Docker image
        run: docker build -f Dockerfile.prod . -t eu.gcr.io/fdk-infra/reference-data:latest

      - name: Run tests
        run: mvn verify --no-transfer-progress

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/fdk-infra/reference-data:latest

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/reference-data
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/fdk-infra/reference-data:latest" -f ./helm/reference-data/values/production.yaml ./helm/reference-data/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_PROD_AUTODEPLOY }}
          project_id: fdk-prod
          location_zone: europe-north1-a
          cluster_name: fdk-prod

      - name: Create backup snapshot
        run: |
          gcloud compute --project fdk-prod disks snapshot "fdk-prod-reference-data" --snapshot-names "autogcs-autodeploy-prod-reference-data-${GITHUB_SHA::8}" --zone "europe-north1-a" &
          wait
          gcloud compute --project fdk-prod snapshots add-labels "autogcs-autodeploy-prod-reference-data-${GITHUB_SHA::8}" --labels="snapshotdays="14""

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo