name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy to staging environment when pull request is created
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2

      # Setup java jdk
      - uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Setup gcloud CLI for image-store
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker eu.gcr.io

      - name: Build Docker image with GitHub commit sha tag
        run: docker build -f Dockerfile.prod . -t eu.gcr.io/digdir-fdk-infra/reference-data:$GITHUB_SHA -t eu.gcr.io/digdir-fdk-infra/reference-data:staging_latest

      - name: Run tests with maven
        run: mvn verify --no-transfer-progress

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/digdir-fdk-infra/reference-data -a

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/new-reference-data
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/reference-data:$GITHUB_SHA" \
          -f ./helm/reference-data/values/staging.yaml \
          ./helm/reference-data/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          export_default_credentials: true

      - name: Deploy to GCP
        run: |
          gcloud container clusters get-credentials digdir-fdk-dev --region europe-north1-a --project digdir-fdk-dev
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Application: New fdk-reference-data | Environment: staging'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
