name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Package with maven
        run: mvn clean package
      - name: Build Docker image
        run: docker build . -t eu.gcr.io/fdk-infra/reference-data:latest
      - name: Run tests
        run: mvn verify